
#------------------------------
#coc.nvim
#------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
hook_add = '''
	source ~/.config/nvim/plugins/coc.vim
'''

#------------------------------
#cs dsで囲い変更
#------------------------------
[[plugins]]
repo = 'tpope/vim-surround'

#------------------------------
#カッコを自動で閉じる
#------------------------------
[[plugins]]
repo = 'cohama/lexima.vim'

#------------------------------
#.を強化
#------------------------------
[[plugins]]
repo = 'tpope/vim-repeat'

#------------------------------
#ウィンドウサイズ変更
#------------------------------
[[plugins]]
repo = 'simeji/winresizer'

#------------------------------
#ワードをブラウザでググる
#------------------------------
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
	nmap <Leader>b <Plug>(openbrowser-smart-search)
	vmap <Leader>b <Plug>(openbrowser-smart-search)
'''

#------------------------------
#見た目を変える
#------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	source ~/.config/nvim/plugins/airline.vim
'''

#------------------------------
#見た目を変える-テーマ追加
#------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#------------------------------
#Git操作
#------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'

#------------------------------
#Gitの変更箇所を表示
#------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'

#------------------------------
#htmlのタグを閉じる
#------------------------------
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
	source ~/.config/nvim/plugins/vim-closetag.vim
'''

#------------------------------
#禅モード
#------------------------------
[[plugins]]
repo = 'junegunn/goyo.vim'

#------------------------------
#インデントを色付け
#------------------------------
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
	let g:indent_guides_enable_on_vim_startup = 1
	let g:indent_guides_auto_colors = 0
	hi IndentGuidesOdd  ctermbg = darkgray
	hi IndentGuidesEven ctermbg = gray
'''
